.PHONY: build validate audit eval site graph track synthesize recap-dry clockbench fair repos hub check help

help:
	@echo "longevity-loop — an AI-native compounding loop for aging science"
	@echo "  make build       Regenerate README.md + docs/ROADMAP.md from data/*.yml"
	@echo "  make validate    Schema-gate data/*.yml"
	@echo "  make audit       Self-audit vs the AI-native loop principles (data/loop.yml)"
	@echo "  make track       Refresh live arXiv/GitHub signal into data/_frontier.yml"
	@echo "  make synthesize  Draft frontier+roadmap proposals into data/_synthesis.md (human-gated)"
	@echo "  make clockbench  Cross-clock disagreement benchmark (measures gaps-analysis G1)"
	@echo "  make fair        Score open aging datasets for FAIR/reproducibility → docs/FAIR.md (G2)"
	@echo "  make repos       Per-repo KG + agentic-tooling generation recipes → docs/REPOS.md (hub)"
	@echo "  make hub         Validate the JIT deep artifacts under hub/ (add --refresh for staleness)"
	@echo "  make check       validate + audit + eval + clockbench + fair + repos + hub + build drift-gate (CI finish line)"

build:
	python3 scripts/build.py

validate:
	python3 scripts/validate.py

audit:
	python3 scripts/audit.py --gate 80

# Roadmap checkbox + before→after eval; fails if a `done` item has no real eval.
eval:
	python3 scripts/eval.py --gate

site:
	python3 scripts/build_site.py
	python3 scripts/build_graph.py

graph:
	python3 scripts/build_graph.py

# Refresh live frontier signal (arXiv + GitHub) into data/_frontier.yml (needs network).
track:
	python3 scripts/track.py

# Draft frontier-update + roadmap-delta PROPOSALS (Europe PMC) into data/_synthesis.md.
# Human-gated: never edits frontier.yml/roadmap.yml — a person promotes what's real.
synthesize:
	python3 scripts/synthesize.py

# Preview the daily recap offline (no API key, no tokens) — proves the pipeline.
# The real article is generated by the daily `recap` GitHub Actions cron.
recap-dry:
	python3 scripts/recap.py --since HEAD~3 --dry-run

# Cross-clock disagreement benchmark (docs/gaps-analysis.md G1). Runs the synthetic
# demo; plug real pyaging/Biolearn clock outputs via `--input clocks.csv`.
clockbench:
	python3 scripts/clockbench.py --demo

# Score the open aging datasets against FAIR → docs/FAIR.md (docs/gaps-analysis.md G2).
fair:
	python3 scripts/fair.py

# Per-repo KG + agentic-tooling generation recipes → docs/REPOS.md (docs/HUB_ARCHITECTURE.md).
repos:
	python3 scripts/repos.py

# Validate the hub's JIT deep artifacts (hub/<repo>/: KG + skill + SHA-stamped manifest).
# `make hub` = offline integrity gate; `python3 scripts/hub_gen.py --refresh` = network staleness.
hub:
	python3 scripts/hub_gen.py --check

# Finish line: data well-formed, still an AI-native loop, executions honestly eval'd (no fake ✅),
# the clock-disagreement + FAIR + repo-recipe + hub artifacts self-verify, and docs match.
check: validate audit eval
	python3 scripts/clockbench.py --selftest
	python3 scripts/fair.py --selftest
	python3 scripts/fair.py --gate
	python3 scripts/fair.py --check
	python3 scripts/repos.py --selftest
	python3 scripts/repos.py --check
	python3 scripts/hub_gen.py --selftest
	python3 scripts/hub_gen.py --check
	python3 scripts/build.py --check
